### ISSUE TITLE
Great-father Winter offers two times the same quest

### ISSUE THREAD

**Issue by GiantCrocodile** [mangosthree/database#12]
I talked to Great-father Winter to complete the quest from the Wonderform Operator but Great-father Winter offers me still two times the quest 'Great-father Winter is Here!'.

**Comment by MadMaxMangos** [comment]
Moved to internal tracker https://www.getmangos.eu/bug-tracker/mangos-three/great-father-winter-offers-two-times-the-same-quest-12-r1459/
