### ISSUE TITLE
Return to Razor Hill CompleteText is wrong

### ISSUE THREAD

**Issue by GiantCrocodile** [mangosthree/database#13]
CompletedText:
Buy a wind rider to the Crossroads from the wind rider master Doras, then bring Gryshka's Letter to Zargh at the Crossroads.

Objectives:
Buy a wind rider to Razor Hill from the wind rider master Doras, then bring Gryshka's Letter to Grimtak at Razor Hill.

Fix:

``` sql
UPDATE `quest_template` SET `CompletedText`='Buy a wind rider to Razor Hill from the wind rider master Doras, then bring Gryshka\'s Letter to Grimtak at Razor Hill.' WHERE  `entry`=6386;
```

**Comment by billy1arm** [comment]
@GiantCrocodile - This has been applied to the db. Thanks
