### ISSUE TITLE
Many level 85 achievements are wrong

### ISSUE THREAD

**Issue by GiantCrocodile** [mangosthree/database#14]
If you achieve level 85 you get a lot of achievements. For example not only for being the first level 85 orc on the realm but also for being the first troll, gnome, etc. which is obviously wrong.

**Comment by MadMaxMangos** [comment]
Moved to internal tracker https://www.getmangos.eu/bug-tracker/mangos-three/many-level-85-achievements-are-wrong-14-r1460/
