### ISSUE TITLE
“Character\Setup\characterLoadDB.sql” with SQL grammar error: 1031

### ISSUE THREAD

**Issue by xgh23** [mangosthree/database#70]
MySQL 5.7.12 execute this file with error code 1031 on line 1825:
CREATE TABLE `game_event_status` (
  `event` smallint(6) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`event`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=FIXED COMMENT='Game event system';

if toke off "ROW_FORMAT=FIXED", then it works.

**Comment by billy1arm** [comment]
@xgh23 fixed in recent commit
