### ISSUE TITLE
Problem of database version

### ISSUE THREAD

**Issue by badmonster-nc** [mangosthree/database#78]
I have installed database and server: 
- https://github.com/mangosthree/database master branch
- https://github.com/mangosthree/server master branch

when I start realmd no problem
```
21000 [realm-daemon]
<Ctrl-C> to stop.

Using configuration file ../etc/realmd.conf.
Login Database total connections: 2
MySQL client library: 5.7.17
MySQL server ver: 5.7.17-0ubuntu0.16.04.1 
MySQL client library: 5.7.17
MySQL server ver: 5.7.17-0ubuntu0.16.04.1 
Added realm id 1, name 'MaNGOS Three Server #1'

```

when I start mangosd:
```
21000 [world-daemon]
<Ctrl-C> to stop.
  __  __      _  _  ___  ___  ___                                 
 |  \/  |__ _| \| |/ __|/ _ \/ __|                             
 | |\/| / _` | .` | (_ | (_) \__ \                             
 |_|  |_\__,_|_|\_|\___|\___/|___/                            
                                        _____ _                   
 For help and support please visit:    |_   _| |_  _ _ ___ ___    
      Website: https://getmangos.eu      | | | ' \| '_/ -_) -_)  
 Forum / Wiki: https://getmangos.eu      |_| |_||_|_| \___\___| 

Using configuration file ../etc/mangosd.conf.
OpenSSL 1.0.2g  1 Mar 2016 (Library: OpenSSL 1.0.2g  1 Mar 2016)
Using ACE: 6.3.3
World Database total connections: 2
Connected to MySQL database root@127.0.0.1:3306/mangos3
MySQL client library: 5.7.17
MySQL server ver: 5.7.17-0ubuntu0.16.04.1 
AUTOCOMMIT SUCCESSFULLY SET TO 1
Connected to MySQL database root@127.0.0.1:3306/mangos3
MySQL client library: 5.7.17
MySQL server ver: 5.7.17-0ubuntu0.16.04.1 
AUTOCOMMIT SUCCESSFULLY SET TO 1
The table `db_version` indicates that your [World] database does not match the expected structure!

  [A] You have database Version: 21
                      Structure: 4
                        Content: 7
                    Description: Update_dbDocs

  [B] You need database Version: 21
                      Structure: 5
                        Content: 1
                    Description: dbscripts_refactor

You must apply all updates after [A] to [B] to use MaNGOS with this database.
These updates are included in the database/World/Updates folder.

Wait 10 secs for continue.
[**************************************************] 100%  
```

**Comment by badmonster-nc** [comment]
I think I find the bug.
In file World/Updates/Rel21/Rel21_05_001_dbscripts_refactor.sql
this condition "IF (@cCurResult = @cOldResult) THEN" never been true

and in file Character/Updates/Rel21/Rel21_03_001_characters_pvpstats.sql
This condition "IF (@cCurResult = @cOldResult) THEN" never been true too

**Comment by billy1arm** [comment]
@badmonster-nc - the message indicates that you need to run all the updates in:

https://github.com/mangosthree/database/tree/master/World/Updates/Rel21

**Comment by badmonster-nc** [comment]
I know, but when I execute updates, this won't do the job. I had to modify this two scripts for the condition always be true

**Comment by billy1arm** [comment]
@badmonster-nc  - Thanks for pointing out the mistake

I have rerun and corrected the scripts:

https://github.com/mangosthree/database/commit/a939212cdfcc9ee4ad8bab9a25c9e6c6654913f6

**Comment by badmonster-nc** [comment]
I have test with your corrections and there is still a problem with this file:
World/Updates/Rel21/Rel21_04_11_Remove_Obsolete_quests.sql

it isn't pass. so, I pass manually sql command and add the new line in db_version. 
Next sql files pass corectly.

**Comment by billy1arm** [comment]
do you have any details of what the error message is for that file ?

**Comment by badmonster-nc** [comment]
Sorry, it was late when I had test sql files... I retest and all scripts works perfectly. I close the issue.

**Comment by billy1arm** [comment]
Excellent news - thank you for finding and reporting the issue.
